### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by ini0n** [tonlabs/tor-service#1]
I tried make requests to https://ton-surf-stand-dev.firebaseapp.com/signing_proof/<random_string>, https://beta.ton.surf/signing_proof/<random_string> and https://ton.surf/signing_proof/<random_string>, it's return 404 or do nothing.

**Comment by Artem-Zhdanov** [comment]
Master branch was stale. I updated it now, Can you git pull and try again ?

**Comment by ini0n** [comment]
Trying, but the same.

1. I'm create Surf account, deploy it, set pin.
2. Generate qr code by `auth.start_authentication` method with params:
`webhook_url` - url to my web server that logs all incoming post requests (for testing)
`pin` - Surf pin.
`context` - some json
`retention_sec` - 600

3. Scan this qr code and is redirected to Surf.
4. Enter my pin.

And nothing happens, no actions in Surf, no requests to my `webhook_url`.

**Comment by Artem-Zhdanov** [comment]
Oh! I understand what you mean.
Surf does not support "Authentication using Surf" yet,  this feature is still in development, sorry, I must mention it :-(
This is why I have  Surf mock in the code https://github.com/tonlabs/tor-service/tree/master/torauth/mocks

**Comment by ini0n** [comment]
Oh, now i got it. Thanks for answer!
